# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collection.Question')),
                ('shuffle_answers', models.BooleanField(default=False)),
            ],
            bases=('collection.question',),
        ),
    ]
